# Generated by Django 5.0.4 on 2025-02-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='specialization',
        ),
    ]
