# Generated by Django 5.1.6 on 2025-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('confirmed', 'Confirmat'), ('cancelled', 'Anulat')], default='pending', max_length=20)),
            ],
        ),
    ]
