# Generated by Django 5.1.6 on 2025-02-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructors.timeslot'),
        ),
    ]
